# classify_seeds.py
import json
import heapq
import numpy as np
import env

SEED_RANGE = range(10000)

# A* on the discrete grid to compute a difficulty score

def heuristic(a, b):
    """
    Manhattan distance between two grid cells.
    This is the classic admissible heuristic for A* on a grid.
    Manhattan is used instead of Euclidean because movements
    are discrete (up/down/left/right + diagonals).
    """
    return abs(a[0] - b[0]) + abs(a[1] - b[1])


def astar_path_length(grid, start, goal, agent_radius):
    """
    Returns the number of nodes in the optimal A* path between start and goal
    on the 'grid', taking the agent radius into account to avoid cells too
    close to walls.

    Args:
        grid      : np.ndarray (size x size), 1 = wall, 0 = free
        start     : tuple (i, j) in integer grid coordinates
        goal      : tuple (i, j) in integer grid coordinates
        agent_radius : float, agent radius in cell units

    Returns:
        int  : path length (number of nodes) if reachable
        float: np.inf if no path exists
    """
    size = len(grid)
    int_r = int(np.ceil(agent_radius))  

    def is_free(i, j):
        """
        A cell is 'free' if:
            1. it is within the bounds of the grid
            2. it is not a wall (grid == 0)
            3. no cell within its neighborhood of radius agent_radius is a wall
                    (reuses the same logic as surroundings_ok in utils.py)
        """
        if not (0 <= i < size and 0 <= j < size):
            return False
        if grid[i][j] == 1:
            return False
        
        for di in range(-int_r, int_r + 1):
            for dj in range(-int_r, int_r + 1):
                ni, nj = i + di, j + dj
                if 0 <= ni < size and 0 <= nj < size and grid[ni][nj] == 1:
                    return False
        return True

    if not is_free(*start) or not is_free(*goal):
        return np.inf

    # Min heap : (f_score, g_score, node)
    # f = g + h  avec g = actual cost from start, h = heuristic toward goal
    open_heap = []
    heapq.heappush(open_heap, (heuristic(start, goal), 0, start))

    # g_scores[node] = best known cost to reach this node from start
    g_scores = {start: 0}

    # 8 directions: up/down/left/right + diagonals
    # Diagonals cost sqrt(2) ≈ 1.414 (actual distance)
    neighbors = [
        ((-1,  0), 1.0), (( 1,  0), 1.0), (( 0, -1), 1.0), (( 0,  1), 1.0),
        ((-1, -1), 1.414), ((-1,  1), 1.414), (( 1, -1), 1.414), (( 1,  1), 1.414),
    ]

    while open_heap:
        f, g, current = heapq.heappop(open_heap)

        if current == goal:
            # g contains the total cost of the path (sum of distances between nodes)
            # We return g as the difficulty score: the longer it is, the harder it is
            return g

        # If we have already found a better path to this node, we skip
        if g > g_scores.get(current, np.inf):
            continue

        for (di, dj), cost in neighbors:
            ni, nj = current[0] + di, current[1] + dj
            neighbor = (ni, nj)
            if not is_free(ni, nj):
                continue
            new_g = g + cost
            if new_g < g_scores.get(neighbor, np.inf):
                g_scores[neighbor] = new_g
                f_score = new_g + heuristic(neighbor, goal)
                heapq.heappush(open_heap, (f_score, new_g, neighbor))

    return np.inf  # No path found



# Difficulty score via the real environment

def score(seed: int, environment: env.NanoEnv) -> float:
    """
    Calculate the difficulty score of a world generated by `seed`.

    The environment is reset with this seed to force generation
    of the world (topology, agent and target positions). Then A* is run
    on the internal discrete grid (_vessel_topology) between the agent
    and the target positions.

    The returned score is the length of the A* path (total cost).
    A short path = easy world. A long or non-existent path = hard world.

    Returns:
        float: length of the optimal path, or np.inf if unreachable
    """
    environment.reset(seed=seed)

    # Continuous positions → integer coordinates on the discrete grid
    # _agent_location and _target_location are in cell units (float)
    # int() truncates to the cell containing the entity center
    start = (int(environment._agent_location[0]), int(environment._agent_location[1]))
    goal  = (int(environment._target_location[0]), int(environment._target_location[1]))

    return astar_path_length(
        environment._vessel_topology,
        start,
        goal,
        environment._agent_radius 
    )



# Classification and export

if __name__ == "__main__":
    environment = env.NanoEnv()

    print(f"Computing scores for {len(SEED_RANGE)} seeds...")
    scores = {}
    unreachable = 0

    for s in SEED_RANGE:
        sc = score(s, environment)
        if sc == np.inf:
            unreachable += 1
        else:
            scores[s] = sc

    environment.close()
    print(f"{len(scores)} reachable seeds, {unreachable} ignored (unreachable).")

    # Partition by percentiles over reachable seeds only
    values = np.array(list(scores.values()))
    p33 = np.percentile(values, 33)
    p67 = np.percentile(values, 67)

    seeds = {
        "easy":   [s for s, v in scores.items() if v <= p33],
        "medium": [s for s, v in scores.items() if p33 < v <= p67],
        "hard":   [s for s, v in scores.items() if v > p67],
    }

    with open("seeds.json", "w") as f:
        json.dump(seeds, f, indent=2)

    print(f"seeds.json generated → easy: {len(seeds['easy'])}, medium: {len(seeds['medium'])}, hard: {len(seeds['hard'])}")